[tools]
lazygit = "latest"
node = "lts"
lazyssh = "latest"
github-cli = "latest"
terraform = "latest"
aws = { version = "latest", symlink_bins = "true" }
vhs = "latest"
uv = "0.12.0"
pipx = "latest"
ruff = "latest"
shellcheck = "latest"
tflint = "latest"
git-cliff = "latest"
glow = "2.1.2"
